# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.eventplanner: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
# for test

spring:
  config:
    activate:
      on-profile: test


  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: events-db
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  customers-service:
    host: localhost
    port: 7001
  venues-service:
    host: localhost
    port: 7002
  participants-service:
    host: localhost
    port: 7003

---

# for docker

spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      username: user
      password: pwd
      database: events-db
      host: mongodb
      port: 27017
      authentication-database: admin
      auto-index-creation: true

server.port: 8080

#spring.datasource.hikari.initializationFailTimeout: 60000

app:
  customers-service:
    host: customers-service
    port: 8080
  participants-service:
    host: participants-service
    port: 8080
  venues-service:
    host: venues-service
    port: 8080